### ISSUE TITLE
Visual design

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#22]
- Design review (Leah, Rachel, Chris)
- illustration (Chris)
- implementation (Maya)

**Comment by mayacakmak** [comment]
Chris’s design: https://projects.invisionapp.com/share/DATGVBRGUH9#/screens/379114326

**Comment by mayacakmak** [comment]
I did a few tests to refresh my memory on where we are with this and what needs to be done. Summary below. I'll work on the styling of the high priority frames this week and update the readme on the visual_design branch for future reference of which frame looks how.

Looks good ============

body/statements: StatementsBodyFrame
words: WordsBodyFrame
selection: EmotionSelectionFrame

Needs polishing =============

(Used within dbt_worksheet_model)

welcome/feedback/browser_check/postq1: FormFrame
consent_disclosure: ConsentDisclosureFrame
mood_induction/short_answer: ShortAnswerFrame
mood_induction/long_answer: TimedLongAnswerFrame
self_report: SelfReportFrame
likert: LikertFrame
intro: IntroFrame
summary/summary_count: SummaryFrameCount
end: EndFrame

Currently not used =====

summary_qual: SummaryFrameQualifier
intro_nographic: IntroFrame
bodymap_color_fwd: BodyMapColorFwdFrame <- broken
bodymap_color: BodyMapColorFrame <- broken
bodymap: BodyMapFrame

**Comment by mayacakmak** [comment]
Okay, a good first version of this is done within the visual_design branch. I left somethings closer to the way they were (versus making them similar to Chris's suggestions) mostly for scalability (e.g. summary page).

One key thing I remembered mid way was to make the style of the "app" and the "study" (i.e. everything else) different--they're still somewhat similar and there is reference to the "reference event" from within the app, which is inconsistent with this separation, but sufficiently distinct. I added a few dummy titles in places for style consistency--their content can be revised.

The code for frames is overall well organized and intuitive but there were some redundancies or inconsistencies I noticed, e.g. LikertFrame is a separate frame but then feedback, which is a FormFrame has Likert items (which are missing an instruction like 'state your agreement' btw). I'm totally fine with these at this stage but noting down.

Lastly there is also inconsistencies and redundancies in how styling is done. Switching to SASS instead of CSS would help a lot because we could define composite classes from existing bootstrap classes, rather than manually add bootstrap classes everywhere (e.g. a lot of frames have a .title which are styled the same using Bootstrap classes). The inconsistency I noticed is related: some thing are styled with custom CSS classes that are then defined within frames.css, others just use bootstrap classes (e.g. noticed this with padding/margins in CSS versus use of mt- mb- my- ml- mr- mx- Bootstrap classes). Again I'm fine leaving it as is for now but something to clean up in the long term.

**Comment by lrperlmu** [comment]
Thanks for working on this! I'll run this code and take a look at the frames when I get a chance, probably tomorrow. 

Is it at a point where you are ready for it to be merged in to master?

I'm fine with switching to SASS or using bootstrap consistently, if you want to implement that. Thanks for pointing this out -- I have no experience with web styling other than plain CSS.

**Comment by lrperlmu** [comment]
Took a look just now, it looks great! The fonts are much more clean and consistent. I especially like changes you made to the summary: the popup is now located relative to the button, has an arrow to the button, and the same button is used to close it.

I think I found a small bug: the frame after the summary (SelfReportFrame) has the background style of the app, but I think we want it to have the style of the study. However, if I click Next from the SelfReportFrame, then navigate Back to it, then it is in the study style.

Reproduction steps:
1. In demo.html, navigate through the study and app to the Summary. (It helps to change constants.js `INDUCTION_TIME_LIMIT` to something small.)
2. In the summary, click Next to go to Identify Your Emotions (SelfReportFrame)
2a. Expected behavior: background changes back to study theme
2b. Actual behavior: background stays in the app theme
3. Click Next to get to Self Assessment (LikertFrame)
4. Click Back to go back to Identify Your Emotions (SelfReportFrame)
4a. Background stays in study theme. This is unexpected, but the correct behavior.

**Comment by mayacakmak** [comment]
Ah yes, good find! I know exactly why, will fix shortly. Do I just cancel the pull request or is there a way to update the pull request with the fix?

**Comment by mayacakmak** [comment]
For CSS->SASS perhaps we can start a separate issue, probably not high priority right now but would be good to remember to do it at some point to clean up the code.

**Comment by lrperlmu** [comment]
I created a new issue #108 

I believe any changes you push to the visual design branch will be automatically incorporated into the pull request.
