### ISSUE TITLE
UserData class and Model data flow.

### ISSUE THREAD

**Issue by sittr7** [lrperlmu/emotional_clarity#63]
existing branch -- pre_post (started by Rachel)

Places to change code:
```
--> class UserData
+ matches(userData, userData): bool
- question
- emotion
- resopnse
- name

--> constructors for specific frame classes (pass in a slug for reporting user data)
* LikertFrame
* SelfReportFrame
* StatementsFrame?
* Frame?

--> get_user_input for every frame class (and anything that it depends on -- including render method)
* Frame
* StatementsFrame
* LikertFrame
* SelfReportFrame

--> DbtWorksheetModel
* constructor
* update
* compute_summary
* fill_in_user_data

--> Logger
* logResponses
```

Also -- LikertFrame when constructed needs a slug by which to log responses. 
* Maybe build this feature into Frame. Selfreport frame will need it too.

**Comment by lrperlmu** [comment]
see whiteboard photograph (on leah's phone)

**Comment by lrperlmu** [comment]
Different kinds of input
* consent form checkboxes
* likertFrame
* selfReportFrame

**Comment by lrperlmu** [comment]
done so far:
* created userdata class
* require frame_data.response_name param in all frame classes that can report responses
still to do:
* use userdata objects instead of dumb data objects for all storage and passing of user data

**Comment by lrperlmu** [comment]
remember to update docs for each place that userdata gets changed.

**Comment by lrperlmu** [comment]
1/28 -- 
to do: 
* update docs for each place that userdata gets changed.
* check behvior for statements with the same question and different emotion. should actually be combining these into one statement with multiple associated emotions. for now, assuming question and name uniquely specify each statement.
* what happens when lookup fails?
* update get_user_input in ~self_report~ and body_map frames.

1/29 
* ~~default value for both likert questions should be undef~~
* ~~bug: hitting next without responding to the likert questions causes an error~~
* ~~bug: likert answers not preserved when going back~~
* **summary is empty**
* theoretically, if we're now keeping Frames as objects, fill_in_data should not be necessary. The frame can transfer user input into its own fields during get_user_input. Or with a callback. But caution: this will couple the model and view aspects of the frame more tightly.

**Comment by lrperlmu** [comment]
# Final Status #

What was done from the initial comment:

### `class UserData` ###
* method: `matches(userData, userData): bool`
* field: `question`
* field: `emotion`
* field: `resopnse`
* field: `name`

_Done. Also added `class UserDataSet`_

### constructors for specific frame classes ###
(pass in a slug for reporting user data)
* LikertFrame
* SelfReportFrame
* StatementsFrame?
* Frame?

_Done. ConsentFrame, LikertFrame, ListBodyFrame, SelfReportFrame_

### get_user_input for every frame class ###
(and anything that it depends on -- including render method)

* Frame
* StatementsFrame
* LikertFrame
* SelfReportFrame

_Did not implement. Instead `get_user_input` methods return Map of  `{statement (string): {'name':name (string), 'response':response (boolean)}`_


### DbtWorksheetModel ###
* constructor
   * _store user data in a `UserDataSet`_
   * _use a response Name when constructing frames_ 
* update
    * _takes in the wacky output of `get_user_input`, passes a `UserDataSet` to the logger_
* compute_summary
    * _transform `this.uds` into the unique format of the summary frame_
* fill_in_user_data 
    * _This method is now dispatched to individual frames_.
    * _Takes in a UserDataSet. Transforms contents into the format that the frame uses for its question/answer data_

### Logger ###
* logResponses
  * _Done. Takes in a UserData object. Logs responses in a subtree under response Name._

**Comment by lrperlmu** [comment]
merged! closing.
