### ISSUE TITLE
required questions

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#90]
* decide which questions are required
* enforce completion of said questions

**Comment by lrperlmu** [comment]
in #100, created the ability to require questions in FormFrame.

So far, the phq-9 questions are required and all others are optional. Need to decide which other questions in the app are required. If they live outside form frame, may need to replace their frame with a FormFrame.

**Comment by mayacakmak** [comment]
Also required questions should have an indicator ("(required)" or red asterisk)

**Comment by mayacakmak** [comment]
Completed implementing required questions with required check for text input; updated button enable/disable with keyup.
Made more questions required. 
In order to not duplicate the required question checking for SelfReportFrame and LikertFrame, changed those pages to use
FormFrame instead-- this required FormFrame to take qualifiers as parameters rather than have fixed qualifiers per question type (event though I left phq as a special type). SelfReportFrame and LikertFrame should be obsolete now. Transferred some of the visual design formatting from these frames into FormFrame.
