### ISSUE TITLE
positive induction based on post mood check results

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#93]

**Comment by mayacakmak** [comment]
Positive mood induction description:

Criteria: For those reporting >3 on either the distress and sadness variables, the system  will automatically guide them through  the following prompts.

“The results of your mood assessment suggest that you may still have lingering negative emotions from recalling a memory. We’d like to have you review another memory, one that made you happy.”

“Think of one event in your life when someone close to you made you feel happy. If you think of more than one event, try to pick one that continues to bring up some pleasant feelings right now”

"For the next few minutes, try to re-experience the event as vividly as you can. Picture the event happening to you all over again. Picture in your “mind’s eye” the surroundings as clearly as possible. See the people or objects; hear the sounds; experience the events happening to you. Think the thoughts that this event makes you think. Feel the same feelings that this event makes you feel. Let yourself react as if you were actually in the middle of it right now. While you re-experience the event, write about what is happening in the situation, how the other person or people involved behaved toward you, and what you are thinking. The screen will advance on its own when the time is up. Begin writing now." 

130 seconds to read prompt and type response
screen advances after time has elapsed -> probably replace this with 'next' button becomes active once time elapsed

**Comment by mayacakmak** [comment]
Implemented as described above (except positive mood induction can also be triggered by the "upset" and "nervous" variables). Positive mood induction frame is added by default and removed if the score is okay though the frame callback function mood_check_compute(). In the process, added 'values' variable to FormFrame to go along with 'qualifiers' so that score computation could be made accurately; updated values of the different qualifiers throughout.
